const os = require("os")
console.log("platform:",os.platform())
console.log("Free Memory available:",os.freemem())
console.log("Total Memory:",os.totalmem())
console.log("CPU Architecture:",os.arch())
console.log("Home directory:",os.homedir())
console.log("Host Name:",os.hostname())
console.log("Windows Version:",os.type())
console.log("CPU cores:",os.cpus().length,"Cores")
